[project]
name = "rl-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium>=1.2.2",
    "matplotlib>=3.10.7",
    "pygame>=2.6.1",
    "torch>=2.9.1",
]
